# Generated by Django 3.1.2 on 2020-10-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(blank=True, default='Note', max_length=250),
        ),
    ]
