# Generated by Django 3.1.2 on 2020-11-03 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_page', '0005_remove_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth',
        ),
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_profile_friends_+', to='main_page.Profile'),
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.ManyToManyField(blank=True, related_name='_friends_friends_+', to='main_page.Friends')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='root', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
